### ISSUE TITLE
Advanced feature: allow for different lengths of mnemonics

### ISSUE THREAD

**Issue by mflaxman** [merland/seedpicker#14]
Why only 11 or 23 words? https://iancoleman.io/bip39/ also allows 14, 17, or 20 words.

I could see an argument for *only* supporting 23 words, but if you're going to allow for less secure mnemonics, more choice seems only better.

Burying everything but 23 words in an advanced section makes a lot of sense.

**Comment by merland** [comment]
The first version supported only 24 word seeds, for UX simplicity reasons and to encourage the safest possible choice. 
Then there was a feature request, issue #8, which was implemented. That decision may have been misguided. 
@freddiemacd: You requested the 12-word version, could you please give some more background to your reasoning?

**Comment by merland** [comment]
For simplicity reasons and for the reason mentioned in #13, only 24 word seeds will be supported from now on.

**Comment by secinthenet** [comment]
@merland I'm interested in a 12-words version because it makes it much easier to remember the seed. Why did you choose to only keep the 24 words version?

**Comment by merland** [comment]
@secinthenet Thanks for the feedback. 
Most hardware wallets use 24 word seeds and I try to keep SeedPicker as simple as possible, in order to not confuse newbies. 
It's a tradeoff of course. I haven't seen many people or projects use 12-word seeds, so it seemed like a good tradeoff to not complicate the user interface.
