### ISSUE TITLE
Reorganize with Specter Desktop users in mind

### ISSUE THREAD

**Issue by merland** [merland/seedpicker#30]
As discussed in btcguide/btcguide.github.io#7, users who want to create a key for Specter Desktop should not have to click on the "Show more"-button. 
The page should be reorganized with that in mind.

**Comment by merland** [comment]
Created an Export To Specter Desktop info box. Known issue: overflow problems when the window is resized too aggressively...
 
@mflaxman, please [check it out](https://seedpicker.net/calculator/last-word.html) and tell me how you think it works together with the guide.

**Comment by mflaxman** [comment]
That looks really good, nice work!

A bunch of minor nits here to use/ignore as you see fit:
*  `(There are other valid words, but this tool always selects the first one, alphabetically.)` -> ` (There are other valid words, but SeedPicker always selects the lexigraphically first one.) `. Also, consider making this some sort of mousover/tooltip element or moving to the advanced section? TMI for normies who can just assume there's only 1 valid checksum and don't need that level of detail.
* `Export To Specter Desktop` -> `Export Public Key Info To Specter Desktop` (newbies may be confused about the public/private component, want to reinforce at all steps)
* `Click the button to save as file.` This sentence probably not needed, there's a big `Download` button next to it.
* `Your last word is ________` -> `Your 24th word is ________`. My CLI tools intentionally support seed phrases of any length, but I understand the desire to KISS. If you're going to require 23+1 words, you can be consistent in your copy.
* Inconsistency for testnet/mainnet: `Extended Public Key in Vpub format (Testnet P2WSH)` vs `Extended Public Key in Zpub format`. I think `SLIP132 Extended Public Key (P2WSH)` is probably the best (being explicit about script type is good but saying `in Vpub format` is overkill when the very next thing starts with `Vpub...`)
* Maybe "Generate sample" should come with some sort of UX modal/popup warning ("only use this for testing"). This could be a separate GH issue since it's a feature request. That way you could also get rid of the clutter of `(only for testing!)`.
* TMI with fingerprint and derivation path descriptions (maybe put under advanced if you want more there)? Or some sort of tooltip/mouseover. There's also inconsistency in style (one uses `-`s for separation and the other uses `()`s). If you do keep the copy, I'd change `root XPUB` to `root extended public key` (always want to be explicit/unambiguous with xpubs and SLIP132 encoding).
* The button is off the page even when the window isn't resized:
![Screen Shot 2020-09-18 at 8 52 27 AM](https://user-images.githubusercontent.com/448644/93605403-511fd600-f98c-11ea-99f9-f763e2729649.png)
* Related: `Vpub` text wraps nicely while advanced section `xpub` does not:
![Screen Shot 2020-09-18 at 8 54 40 AM](https://user-images.githubusercontent.com/448644/93605639-a1973380-f98c-11ea-9e27-9adca5dd7e2a.png)

**Comment by merland** [comment]
Thanks for excellent feedback! It seems our thoughts are pretty well aligned, because a majority of these points have crossed my mind once or twice :) But many are new and insightful! 
Let's consider this an 80/20 solution for now. It works but needs a lot of polishing.  I can't put in more hours right now but I'll be back soon 👍

**Comment by merland** [comment]
Made some copy touchups, researching the best way to display tooltip (or similar) before any bigger changes.

**Comment by merland** [comment]
Addressed some of these points. Simplified the layout and added some tooltips. More eyeballs appreciated! @mflaxman

**Comment by mflaxman** [comment]
Love all the improvements!


Minor stuff: tooltip/mouse-over doesn't seem supported on mobile, and download button can be formatted funky.
![image](https://user-images.githubusercontent.com/448644/94343981-a473d300-ffe1-11ea-81d9-72ba154eb100.jpeg)

Obviously mobile isn't a normal use-case but people like to try stuff out on their phones first.

**Comment by merland** [comment]
Thanks, great!

The tooltips seem to work on all browsers except Safari, which I am guessing you used? I tried Chrome and Safari on Iphone and Firefox and Chrome on Android. 

The download button does indeed look funky on all browsers. 

I'll dig deeper.

**Comment by mflaxman** [comment]
> The tooltips seem to work on all browsers except Safari, which I am guessing you used? I tried Chrome and Safari on Iphone and Firefox and Chrome on Android.

Ya, it's just on safari mobile (iOS) that I'm having this problem, safari desktop (MacOS) works well. Chrome/Firefox on iOS LGTM.

**Comment by mflaxman** [comment]
This is looking really good!

I was talking with @stephanlivera last night about this and he was suggesting a video/screencast of someone using seedpicker might be really helpful. I may put that together in the future, or if someone else does I'd happily link/embed it on my guide.

--

Doing some more playing around I discovered a few very minor remaining items (apologies if these are conscious decisions/disagreements)...

Mainnet page reads:
`Extended Public Key in Zpub format`
Testnet page reads:
`Extended Public Key in Vpub format (Testnet P2WSH)`

Why the difference in copy? I can understand only saying testnet on the testnet one, but they're both p2wsh. Related idea: add to the `Show more (for advanced users)` only section the script type (P2WSH)? That seems appropriate for advanced users only but also good to be explicit there (only).

FWIW I still think "Extended Public Key in Zpub/Vpub format" is strange (it's obviously Zpub/Vpub, it starts with Zpub/Vpub!). If you want to be explicit you could say `SLIP132 Extended Public Key` and then do a mouseover that explains and/or links to what SLIP132 is.

Maybe it's just me but "Complete seed phrase" feels a little ambiguous, as it could be a command/instruction like "please complete your seed phrase." Perhaps something like "full seed phrase", "entire seed phrase", "whole seed phrase", "seed phrase with 24th word", etc would be unambiguous.

**Comment by merland** [comment]
Good points, and thanks for keeping them coming! 

The difference in copy is probably just an oversight, or something that was left behind by mistake. After a while you get blind to these things, until more eyes look at it. Will fix. 

I do remember struggling with coming up with good copy when it comes to XPUBs. Zpubs and Xpubs are XPUBs but not xpubs (guess it depends...). It is an overloaded term, and probably very confusing for newbies. That is why "Extended Public Key" was used and not only "Zpub" or "VPub".  Now that tooltips are available I'll definitely try to move some more info into them.

Regarding the "Complete seed phrase", really good point! I hadn't noticed the ambiguity before, English is not my first language. I think "Full seed phrase" sounds good!  
    
Really appreciate your feedback!

**Comment by merland** [comment]
Forgot to comment about the screencast. Sounds like a fantastic idea. 
Maybe the whole process of printing and cutting pieces of paper from your guide should be filmed as well... And you should get a real monkey to do the draw!

**Comment by stephanlivera** [comment]
Right, a good style to copy is this "Keep it Simple Bitcoin" YouTube guy,
he basically cuts forward to the relevant part in the clip, so the video
ends up being very short and sweet. Much more 'palatable' for the newbie or
intermediate bitcoiner if its just a short video rather than a really long
screencast. https://www.youtube.com/channel/UC6MJHe8zOJb8VIwUiWPzLVg

**Comment by merland** [comment]
I had to simplify the download button to get it to look OK on both web and mobile. Will research a better solution once I have some more time... 

The tooltips now show up on Safari, but there is an annoying behavior when trying to getting rid of them. This is a known issue in Bulma, details [here](https://github.com/Wikiki/bulma-tooltip/issues/25)). 
Clicking another question mark or the input field closes the previous tooltip. 
I'll investigate some more.

**Comment by merland** [comment]
Tooltips on Safari should work now :)

**Comment by mflaxman** [comment]
Nice, this is looking slick!
